[build]
  # Run the build inside the React app folder
  base = "mindbridge-client"
  command = "npm run build"
  # Folder that Vite outputs after build - relative to base directory
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
